---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaostoolkit-kopf-crd-watcher
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - kopf.dev
  resources:
  - clusterkopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - delete
  - list
  - patch
- apiGroups:
  - admissionregistration.k8s.io/v1
  - admissionregistration.k8s.io/v1beta1
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - pods
  - deployments
  - endpoints
  - services
  verbs:
  - create
  - get
  - delete
  - list
  - patch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - "create"
  - "get"
  - "delete"
  - "list"
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - list
- apiGroups:
  - chaostoolkit.org
  resources:
  - chaosexperiments
  - chaosexperiments/finalizers
  verbs:
  - list
  - watch
  - patch
  - update
- apiGroups:
  - policy
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - list
  - get
  - use
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaostoolkit-kopf-crd-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaostoolkit-kopf-crd-watcher
subjects:
- kind: ServiceAccount
  name: chaostoolkit-crd
  namespace: chaostoolkit-crd
