---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaostoolkit-kopf-crd-watcher
rules:
- apiGroups:
  - kopf.dev
  resources:
  - kopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - pods
  verbs:
  - create
  - get
  - delete
  - list
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - list
- apiGroups:
  - chaostoolkit.org
  resources:
  - chaosexperiments
  - chaosexperiments/finalizers
  verbs:
  - list
  - watch
  - patch
  - update
- apiGroups:
  - policy
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaostoolkit-kopf-crd-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaostoolkit-kopf-crd-watcher
subjects:
- kind: ServiceAccount
  name: chaostoolkit-crd
