---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: chaostoolkit-crd

commonLabels:
  role: chaosengineering
  provider: chaostoolkit
  app: chaostoolkit-crd

resources:
- ns.yaml
- ../../base
- ../../base/rbac
- ../../base/sec/pod
