---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: chaostoolkit-crd
spec:
  privileged: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - configMap
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaostoolkit-psp
rules:
- apiGroups:
  - policy
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - chaostoolkit-crd
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaostoolkit-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaostoolkit-psp
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
  namespace: keos-chaostoolkit-crd
#- apiGroup: rbac.authorization.k8s.io
#  kind: Group
#  name: system:serviceaccounts
#  namespace: chaostoolkit-crd
- kind: ServiceAccount
  name: chaostoolkit-crd
  namespace: keos-chaostoolkit-crd
---
# This is the PSP for containers running the chaos experiments (not the CRD)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: chaostoolkit-run
spec:
  privileged: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - configMap
  - secret