---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaostoolkit-env
  namespace: chaostoolkit-run
data:
  ENDPOINT_URL:   "https://httpstat.us/200?sleep=2000"
  EXPERIMENT_URL: "https://raw.githubusercontent.com/open-chaos/experiment-catalog/master/local/url-responds/url-responds.json"
---
apiVersion: chaostoolkit.org/v1
kind: ChaosToolkitExperiment
metadata:
  name: my-chaos-exp
  namespace: chaostoolkit-crd
spec:
  pod:
    experiment:
      asFile: false