name: 'Build & Test'
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --no-cache-dir --prefer-binary --upgrade pip
        pip install --no-cache-dir --prefer-binary -r requirements.txt -r requirements-dev.txt
    - name: Checking the code syntax
      run: |
        pylama controller.py
    - name: Run tests
      run: |
        pip install -e .
        pytest tests/

  ci:
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: './manifests/overlays/generic-rbac'
          kustomize_output_file: "operator.yaml"
          enable_alpha_plugins: true
      - name: 'Start K3s lightweight Kubernetes cluster'
        uses: debianmaster/actions-k3s@v1.0.1
        id: k3s
        with:
          version: 'v1.18.2-k3s1'
      - name: 'Check K3s server is up&running'
        run: |
          sleep 10
          kubectl get nodes
          kubectl get pods -A
      - name: 'Install the operator'
        run: |
          kubectl apply -f operator.yaml
      - name: 'List namespaces'
        run: |
          kubectl get ns
      - name: 'Check operator pod is running'
        run: |
          sleep 60
          kubectl -n chaostoolkit-crd get deploy
          kubectl -n chaostoolkit-crd get pods
      - name: 'Create the example experiment'
        run: |
          kubectl apply -f examples/basic.yaml
      - name: 'Check the chaostoolkit experiment'
        run: |
          kubectl -n chaostoolkit-crd get ctk
      - name: 'Wait for experiment pod to run (docker pull & run experiment)'
        run: |
          sleep 120
          kubectl -n chaostoolkit-run get pods
      - name: 'Check operator logs'
        run: |
          kubectl -n chaostoolkit-crd logs -l app=chaostoolkit-crd
      - name: 'Check chaostoolkit pod logs'
        run: |
          kubectl -n chaostoolkit-run logs -l app=chaostoolkit
      - name: 'Assert experiment succeeded'
        run: |
          kubectl -n chaostoolkit-run get pods | grep chaos | grep Completed
