name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
      name: Set up Docker Buildx
    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
        username: chaostoolkit
        password: ${{ secrets.DOCKER_PWD }}
    - name: Docker images metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          chaostoolkit/k8scrd
        tags: |
          type=raw,value=latest
          type=semver,pattern=${{steps.latest_tag.outputs.git_latest_tag}}
        labels: |
          org.opencontainers.image.version=${{steps.latest_tag.outputs.git_latest_tag}}
    - name: Build and push images
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: mode=max
        sbom: true
